In [85]:
# convert aspect from [0,360] to [0,180]
# references: 
# https://livebook.manning.com/book/geoprocessing-with-python/chapter-9/81
# https://gis.stackexchange.com/questions/58517/python-gdal-save-array-as-raster-with-projection-from-other-file
# https://gis.stackexchange.com/questions/319249/inserting-nodata-value-using-gdal

import os
import numpy as np
import pandas as pd
from osgeo import gdal
gdal.UseExceptions()

asp_360 = '/gpfs/fs1/work/hongli/research/discretization/scripts/step2_dem_postprocess/aspect_buf_100m_neg1.tif'
asp_180 = '/gpfs/fs1/work/hongli/research/discretization/scripts/step2_dem_postprocess/aspect_buf_100m_180deg.tif'
nodata = -9999

in_ds = gdal.Open(asp_360)
in_band = in_ds.GetRasterBand(1) 
asp_360_data = in_band.ReadAsArray()
asp_180_data = np.where(asp_360_data>180, 360-asp_360_data, asp_360_data)
array = np.where(asp_180_data<-1, np.nan, asp_180_data)

gtiff_driver = gdal.GetDriverByName('GTiff')
out_ds = gtiff_driver.Create(asp_180, in_band.XSize, in_band.YSize, 1, in_band.DataType) #
out_ds.SetProjection(in_ds.GetProjection())
out_ds.SetGeoTransform(in_ds.GetGeoTransform())

out_ds.GetRasterBand(1).WriteArray(array)
out_ds.GetRasterBand(1).SetNoDataValue(nodata) # set nodata value of the band
out_ds.FlushCache() # Write to disk
del out_ds # delete the variable, so IDE/interactive Python releases the dataset object when the script finishes.

print('Done')

Done


In [78]:
# asp_360_data = read_raster(asp_360,'aspect','Area')
np.where(array!=-9999)

(array([1761, 1761, 1761, ..., 4239, 4239, 4240]),
 array([4189, 4190, 4191, ..., 2710, 2711, 2711]))

In [79]:
asp_360_data[4240,2711],array[4240,2711]

(135.0, 135.0)

In [86]:
in_ds = gdal.Open(asp_180)
in_band = in_ds.GetRasterBand(1) 
asp_180_data = in_band.ReadAsArray()
asp_180_data

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [82]:
asp_180_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [43]:
np.shape(in_band.ReadAsArray())

(8223, 6397)

In [44]:
a=in_band.ReadAsArray()

In [45]:
a

array([[-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       ...,
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]], dtype=float32)

In [ ]:
np.where(a)